### ISSUE TITLE
Why don't you use the multi-domain training method?

### ISSUE THREAD

**Issue by deeplearnerJHB** [aseuteurideu/ADNet_pytorch#1]
Thank you for your code which is very inspired to me. However, I have some problems. Why don't you use the multi-domain training like in the initial Matlab code. In addition, I think you you have a wrong about setting the stop action. It is 8 rather than 9.

**Comment by aseuteurideu** [comment]
Actually I am beginner in Matlab, so I prefer to see the paper more and just refer to Matlab for small functions and overall structure. And the paper doesn't mention about the multi-domain as far as I know. So thanks a lot for your notification.

Anyway, I just looked the Matlab code in more detail. It is the part where they use separate [_dummy_score_net_](https://github.com/hellbell/ADNet/blob/master/train/adnet_train_SL.m#L63) for each _train_db_, right?

**Comment by deeplearnerJHB** [comment]
Hello. I have a problem. Have you used the uploaded parameters in Matlab ADNet project to test the performance? The author said that he uses the vot + alov300 to train, but the released project just uses the vot. I don't know why? I also want to know how much the training videos that they used to obtain their uploaded model parameters?

**Comment by aseuteurideu** [comment]
Sorry for the late response. Yes, I realized that they don't use the ALOV300 in their Matlab implementation. For now, my target is using VOT like their Matlab implementation until I reach somewhat reasonable performance (at least like in their implementation, although less than the paper performance). I tried to train with their code and reached around 76 mAP

**Comment by aseuteurideu** [comment]
@deeplearnerJHB I have updated the code with multi-domain and the stop action index. For the dataset, I will consider a separate issue. See README for updated information
