### ISSUE TITLE
For pre-trained weights 

### ISSUE THREAD

**Issue by hranYin** [aseuteurideu/ADNet_pytorch#2]
Sorry to disturb you. 
Could you please release some pre-trained weights by the adnet_train_sl.py and adnet_train_rl.py for testing,  because there are not enough GPUs to train by myself. Thank you very much!
If possible, please hxy876@student.bham.ac.uk.

**Comment by aseuteurideu** [comment]
Hi.. Here is the weight download link
[RL weight](https://www.dropbox.com/s/gmio90qzcj4h20x/ADNet_RL_.pth?dl=0)
[SL weight](https://www.dropbox.com/s/3unoop8czu13sic/ADNet_SL_.pth?dl=0)
